# Generated by Django 2.1.2 on 2018-10-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_fighters'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='to_rank_down',
            field=models.IntegerField(default=-3),
        ),
        migrations.AddField(
            model_name='ranks',
            name='to_rank_up',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_rank',
            field=models.IntegerField(default=1),
        ),
    ]
