# Generated by Django 2.1.2 on 2018-10-16 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_player_player_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Character', to='leaderboard.Fighters'),
        ),
    ]
